### PR TITLE
Update for Julia 0.4 & add a few tests

### PR DESCRIPTION
**Pull request by nignatiadis**
- This puts the package in the standard form returned by `Pkg.generate()` in Julia 0.4 (except appveyor). 
- Deprecation warnings have been fixed. 
- This adds a few additional tests, which we had originally written with @julian-gehring for the [MultipleTesting.jl](https://github.com/julian-gehring/MultipleTesting.jl) package. 
- Special-casing of `n <= 1`.

### CODE REVIEW

**Comment by ajtulloch** [comment]
Looks awesome, thanks!

**Comment by nignatiadis** [comment]
Great, thanks a lot for merging this so quickly! Would it be possible to also tag the new version on METADATA?

**Comment by nignatiadis** [comment]
Hi! Bumping this to ask if the changes could be tagged on METADATA.jl?

**Comment by ajtulloch** [comment]
How do I do that? Would you like to take over ownership of this package (not even sure if that's a thing in Julia) and do that?

**Comment by nignatiadis** [comment]
I have not done it before either, but I think one just types `Pkg.tag("Isotonic", v"0.0.2")`. This generates a tag in the Isotonic package (which also has to be pushed to Github) and updates the METADATA.jl package, for which one has to submit a pull request after.

In Julia it should be straightforward for me to do this. You could either add me as a contributor or I could point METADATA.jl to my fork, whichever you prefer!

**Comment by ajtulloch** [comment]
Thanks @nignatiadis , I've added you as a collaborator, but feel free to take this package as you will. Thanks so much.

**Comment by nignatiadis** [comment]
Thank you @ajtulloch for this great package and for being so responsive!

**Pull request merged**
